"""create_reel_interactions_tables

Revision ID: 16170429d8fa
Revises: 9e5a95738178
Create Date: 2026-05-20 18:15:51.886405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision: str = '16170429d8fa'
down_revision: Union[str, Sequence[str], None] = '9e5a95738178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_comments',
    sa.Column('id', app.core.database.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reel_id', app.core.database.GUID(), nullable=False),
    sa.Column('author_id', app.core.database.GUID(), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reel_comments_author_id'), 'reel_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_reel_comments_reel_id'), 'reel_comments', ['reel_id'], unique=False)
    op.create_table('reel_likes',
    sa.Column('reel_id', app.core.database.GUID(), nullable=False),
    sa.Column('buyer_id', app.core.database.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reel_id', 'buyer_id')
    )
    op.create_table('reel_saves',
    sa.Column('reel_id', app.core.database.GUID(), nullable=False),
    sa.Column('buyer_id', app.core.database.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reel_id', 'buyer_id')
    )
    op.create_table('reel_views',
    sa.Column('reel_id', app.core.database.GUID(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reel_id', 'ip_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reel_views')
    op.drop_table('reel_saves')
    op.drop_table('reel_likes')
    op.drop_index(op.f('ix_reel_comments_reel_id'), table_name='reel_comments')
    op.drop_index(op.f('ix_reel_comments_author_id'), table_name='reel_comments')
    op.drop_table('reel_comments')
    # ### end Alembic commands ###
