"""buyer and seller profiles

Revision ID: 4ee20dfafb4c
Revises: 1a0bb8d155d6
Create Date: 2026-05-19 23:06:05.165558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee20dfafb4c'
down_revision: Union[str, Sequence[str], None] = '1a0bb8d155d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('seller_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shop_name', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('shipping_days', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('instagram_handle', sa.String(length=30), nullable=True),
    sa.Column('payout_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_profiles')
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###
