"""create_reels_table

Revision ID: 9e5a95738178
Revises: 484828734e4e
Create Date: 2026-05-20 18:09:26.310181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision: str = '9e5a95738178'
down_revision: Union[str, Sequence[str], None] = '484828734e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reels',
    sa.Column('id', app.core.database.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seller_id', app.core.database.GUID(), nullable=False),
    sa.Column('product_id', app.core.database.GUID(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('like_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reels_product_id'), 'reels', ['product_id'], unique=False)
    op.create_index(op.f('ix_reels_seller_id'), 'reels', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reels_seller_id'), table_name='reels')
    op.drop_index(op.f('ix_reels_product_id'), table_name='reels')
    op.drop_table('reels')
    # ### end Alembic commands ###
